export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const SUBMIT_POST_PENDING = 'SUBMIT_POST_PENDING';
export const SUBMIT_POST_FAILURE = 'SUBMIT_POST_FAILURE';
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS';
export const DELETE_POST = 'DELETE_POST';